version = 0.1

[default.deploy.parameters]
stack_name = "lyra"
resolve_s3 = true
s3_prefix = "lyra"
region = "eu-south-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-south-2"
