AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lyra Members API
Resources:
  LyraMembersApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      FunctionName: lyra-members-api
      Timeout: 10
      CodeUri: ./target/members-api-0.0.1-SNAPSHOT-native-zip.zip
      Handler: NOP
      Runtime: provided.al2023
      Architectures:
        - arm64
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 10000
            PayloadFormatVersion: '1.0'

Globals:
  Api:
    EndpointConfiguration: REGIONAL
Outputs:
  LyraMembersApi:
    Description: Lyra Members API URL
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: LyraMembersApi
