logging.level.root=info
logging.structured.format.console=ecs
management.endpoint.health.probes.enabled=true
spring.application.group=lyra
spring.application.name=members-api
spring.jpa.properties.javax.persistence.schema-generation.database.action=validate
#---
spring.config.activate.on-profile=embedded
logging.level.com.sagittec=debug
management.otlp.logging.export.enabled=false
management.otlp.metrics.export.enabled=false
management.otlp.tracing.export.enabled=false
spring.h2.console.enabled=true
spring.jpa.properties.javax.persistence.schema-generation.database.action=create-drop
spring.jpa.show-sql=true
