logging.level.root=info
spring.application.group=com.sagittec.lyra
spring.application.name=members-api
spring.data.rest.base-path=v@parsedVersion.majorVersion@
spring.jackson.default-property-inclusion=non_empty
spring.mvc.problemdetails.enabled=true
spring.reactor.context-propagation=auto
spring.threads.virtual.enabled=true
spring.web.resources.add-mappings=false
#---
spring.config.activate.on-profile=embedded
logging.level.com.sagittec=debug
management.logging.export.otlp.enabled=false
management.otlp.metrics.export.enabled=false
management.tracing.export.otlp.enabled=false
spring.h2.console.enabled=true
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=create
spring.jpa.show-sql=true
#---
spring.config.activate.on-profile=!embedded
logging.structured.format.console=ecs
management.endpoint.health.probes.enabled=true
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=create
