name: Build Docker image

on:
  workflow_call:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
      - name: Set-up GraalVM
        uses: graalvm/setup-graalvm@6f3fa030c4b8f77c1f554a860f593a654538fa38
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: 'maven'
      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: ./mvnw -B spring-boot:build-image -Pnative
