name: Build source code

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Check Maven artifact
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - name: Set-up GraalVM
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: 'maven'
      - name: Cache SonarCloud packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build & Test
        run: ./mvnw -B clean verify
      - name: Run SonarCloud analysis
        if: github.actor != 'dependabot[bot]'
        run: >
          ./mvnw -B sonar:sonar
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=lyra-oss_members-api
          -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
