name: Build Docker image

on:
  workflow_call:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - name: Set-up GraalVM
        uses: graalvm/setup-graalvm@60c26726de13f8b90771df4bc1641a52a3159994
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: 'maven'
      - name: Log in to the Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: ./mvnw -B spring-boot:build-image -Pnative
