name: Build Code

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/dependabot-code.yml'
      - '.github/dependabot.yml'

jobs:
  build-source-code:
    permissions:
      contents: read
      security-events: write
    name: Build source code
    uses: ./.github/workflows/build-code.yml
    with:
      mutation-scope: full
    secrets: inherit
  build-application-deliverable:
    permissions:
      contents: read
      security-events: write
      packages: write
      id-token: write
      attestations: write
    needs: build-source-code
    name: Build application deliverable
    uses: ./.github/workflows/build-docker.yml
    with:
      push-image: true
      run-verification: true
    secrets: inherit
  clean-old-docker-images:
    needs: build-application-deliverable
    name: Clean up old Docker images
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55
        with:
          package-name: 'members-api'
          package-type: 'container'
          min-versions-to-keep: 2
