name: Build Code

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/dependabot-code.yml'
      - '.github/dependabot.yml'

permissions:
  contents: read
  pull-requests: read
  security-events: write
  packages: write

jobs:
  build-source-code:
    name: Build source code
    uses: ./.github/workflows/build-code.yml
    secrets: inherit
  build-application-deliverable:
    needs: build-source-code
    name: Build application deliverable
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
  clean-old-docker-images:
    needs: build-application-deliverable
    name: Clean up old Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          package-name: 'members-api'
          package-type: 'container'
          min-versions-to-keep: 2
